/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./Movies.js",
    "./Search.js",
    "./ListView.js",
    "./LoginScreen.js",
    "./Profile.js",
    "./MovieDetail.js",
    "./VideoList.js",
    "./RatingModal.js",
    "./PersonProfile.js",
    "./PersonImageList.js",
    "./OtherCredits.js",
    "./MoreMovieAndShowImageList.js",
    "./Shows.js",
    "./ShowDetails.js",
    "./SeasonDetails.js",
    "./EpisodeDetails.js",
    "./GridView.js",
    "./Discover.js",
    "./DiscoverResults.js",
    "./HorizontalFlatList.js",
    "./FavoriteRatingWatchList.js",
    "./Setting.js",
    "./ForYouMovie.js",
    "./ForYouMovieSeeMore.js",
    "./FavActorList.js",
    "./ForYouTv.js",
    "./ForYouTvSeeMore.js",
    "./Review.js",
    "./SplashScreen.js",
    "./Suggestions.js",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
